name: flutter_location_search
description: Package that provides Place search with history of latest location searched using Open Street Map. It is easy to custom and can be displayed in fullscreen or overlay mode
version: 1.1.4
homepage: https://github.com/KomInc/flutter_location_search
license: MIT

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.18.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.0.0
  http: ^0.13.5
  intl: ^0.18.0
  logger: ^2.0.1
  shared_preferences: ^2.0.16
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0