name: flutter_location_search
description: Package that provides Place search using Open Street Map
version: 1.0.1
homepage: https://github.com/KomInc/flutter_location_search
license: MIT

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  http: ^0.13.5
  intl: ^0.18.0
  latlong2: ^0.8.1
  logger: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter